### ISSUE TITLE
Загадывание числа в игре быки и коровы (Ввод числа)

### ISSUE THREAD

**Issue by neyron8** [neyron8/TRPO-2018-games-library#12]
Тут и ничего добавить, все есть в названии

**Comment by SlowKingg** [comment]
Реализовал в коммите [{25f39a4}](https://github.com/neyron8/TRPO-2018-games-library/commit/25f39a40063ed0f03d1e6fc34007a4d5f1eefd39)

**Comment by SlowKingg** [comment]
# Не выполнил условие не повторяющихся цифр

**Comment by SlowKingg** [comment]
Исправил в коммите [{13fda70}](https://github.com/neyron8/TRPO-2018-games-library/commit/13fda703995d7871f1dd9d66ba7a923d8610cebd)

**Comment by SlowKingg** [comment]
# Вывод в функции ввода

**Comment by SlowKingg** [comment]
# Исправил в коммите [{9952dd2}](https://github.com/neyron8/TRPO-2018-games-library/commit/9952dd2b7837bd3e8106c7453d956c171ee41e23)
### Вывод вынесен в функцию print_error
