### ISSUE TITLE
Разделение логики и ввода в функциях

### ISSUE THREAD

**Issue by neyron8** [neyron8/TRPO-2018-games-library#16]
Написанные функции непригодны для тестов. Их нужно переписать.

**Comment by SlowKingg** [comment]
# Исправил в коммите [{ca99bf8}](https://github.com/neyron8/TRPO-2018-games-library/commit/ca99bf8f2533a8189cc718f1850973ba65f966b4)
### Вывод вынесен в функцию print_error
### Проверка из других функций (логика) перенесена в функцию check_number

**Comment by SlowKingg** [comment]
# Исправил в коммите [{ca99bf8}](https://github.com/neyron8/TRPO-2018-games-library/commit/ca99bf8f2533a8189cc718f1850973ba65f966b4)
### Вывод вынесен в функцию print_error
### Проверка из других функций (логика) перенесена в функцию check_number
