### ISSUE TITLE
Баг с вводом числа в игре "Быки и Коровы"

### ISSUE THREAD

**Issue by Furtilamin** [neyron8/TRPO-2018-games-library#17]
При вводе числа, имеющего более 4-х разрядов, выводятся некорректные сообщения о том, что число имеет больше 4-х разрядов, а затем то, что в числе меньше 4-х разрядов. Необходимо исправить!

**Comment by SlowKingg** [comment]
# Исправил в коммите [{4f750a7}](https://github.com/neyron8/TRPO-2018-games-library/commit/4f750a7921782f87595817ff326fdd8f9ad9eb95)
