### ISSUE TITLE
Определение очерёдности игроков.

### ISSUE THREAD

**Issue by neyron8** [neyron8/TRPO-2018-games-library#7]
Определение очереди игры, то есть кто будет ходить первым, а кто вторым.

**Comment by SlowKingg** [comment]
Реализовал в коммите [(c66feec)](https://github.com/neyron8/TRPO-2018-games-library/commit/c66feec5c114888e34f706f84d29f64f30a05a5a

**Comment by SlowKingg** [comment]
# Функция оказалась ненужной
