### ISSUE TITLE
Проверка корректности числа. (Bulls and Cows)

### ISSUE THREAD

**Issue by neyron8** [neyron8/TRPO-2018-games-library#8]
По правилам игры число должно быть 4-х значным. Функция должна проверить корректность числа.

**Comment by SlowKingg** [comment]
Реализовал в коммите [{178d57c}](https://github.com/neyron8/TRPO-2018-games-library/commit/178d57c5360532401d06a1113c01cdf27db7f702)

**Comment by SlowKingg** [comment]
# Не выполнил условие не повторяющихся цифр

**Comment by SlowKingg** [comment]
# Исправил в коммите [{13fda70}](https://github.com/neyron8/TRPO-2018-games-library/commit/13fda703995d7871f1dd9d66ba7a923d8610cebd)

**Comment by SlowKingg** [comment]
# Вывод в функции проверки числа

**Comment by SlowKingg** [comment]
# Исправил в коммите [{4238454}](https://github.com/neyron8/TRPO-2018-games-library/commit/4238454eb2e902e6cd50a84bf4186062ab7658b9)
### Вывод вынесен в функцию print_error
